# .github/ISSUE_TEMPLATE/config.yml

blank_issues_enabled: false
contact_links: []

issue_templates:
  - name: "Bug Report"
    description: "Signaler un bug dans le projet."
    title: "[BUG] "
    labels: ["bug"]
    assignees: []
    body: .github/ISSUE_TEMPLATE/bug_report.md

  - name: "Task"
    description: "Créer une tâche pour le développement d'une fonctionnalité."
    title: "[TASK] "
    labels: ["task"]
    assignees: []
    body: .github/ISSUE_TEMPLATE/task_template.md