// TE probability scores for each classification label
// Higher values indicate stronger association with ecological transition (TE)
export const TE_PROBABILITIES: Record<string, number> = {
  "Sobriété énergétique": 1.0,
  "Energie éolienne": 1.0,
  "Energies renouvelables particuliers, énergies renouvelables citoyennes (ENRc)": 1.0,
  "Energie hydraulique": 0.95,
  "Agrivoltaïsme, panneaux solaires sur le bâti": 1.0,
  "Champs de panneaux solaires": 1.0,
  "Energies renouvelables": 1.0,
  Réseaux: 0.3,
  "Réseau électrique": 0.5,
  "Réseau de chaleur": 0.9,
  "Réseau de froid": 0.85,
  "Remplacement chauffage": 0.8,
  "Chauffage bois": 0.85,
  "Pompes à chaleur": 0.9,
  "Chauffage biogaz": 0.9,
  "Chauffage géothermie": 0.95,
  "Chauffage résidus agricoles et alimentaires": 0.9,
  "Chauffage solaire thermique": 0.95,
  "Combustibles Solides de Récupération (CSR)": 0.8,
  Biocarburants: 0.85,
  "Eclairage intérieur ou extérieur d'un bâtiment ou d'un équipement sportif": 0.4,
  "Eclairage public": 0.4,
  "Filière bois": 0.7,
  "Filière hydrogène": 0.9,
  "Filières agricoles à bas niveau d'impact": 0.95,
  "Valorisation des biodéchets": 0.95,
  "Elevage à l'herbe": 0.8,
  "Rémunération des services environnementaux (PSE notamment)": 0.95,
  "Diminution de l'usage des pesticides": 1.0,
  "Préservation du patrimoine naturel": 0.95,
  Haies: 0.85,
  "Lutte contre les espèces exotiques envahissantes": 0.9,
  "Réseau d'aires protégées et d'aires de protection forte": 0.95,
  "Espèces et habitats à enjeux de conservation": 0.95,
  "Solutions Fondées sur la Nature": 1.0,
  "Atlas de la biodiversité": 0.95,
  "Points noirs de continuité écologique": 0.95,
  "Clauses environnementales dans les marchés publics": 0.9,
  "Projets alimentaires territoriaux (PAT)": 0.8,
  "Education et la sensibilisation à une alimentation locale, durable, diversifiée et de qualité": 0.75,
  "Infrastructures pour les circuits alimentaires et à la transformation locale": 0.7,
  "Tarification incitative des déchets pour les particuliers": 0.9,
  "Gestion des déchets": 0.8,
  "Réemploi des contenants": 0.9,
  "Réseau d'eau potable, sobriété eau potable": 0.7,
  "Qualité de l'eau, captages prioritaires": 0.75,
  "Réseau d'assainissement": 0.5,
  "Gestion des inondations": 0.6,
  "Gestion des eaux pluviales": 0.7,
  "Bornes et poteaux incendies, défense extérieure contre l'incendie (DECI)": 0.05,
  "Dispositif de stockage d'eau": 0.5,
  "Eau souterraine": 0.65,
  "Mers et océans": 0.7,
  "Sobriété immobilière": 0.85,
  Bioconstruction: 0.9,
  "Prévention, réemploi et recyclage des déchets du bâtiment et des travaux publics": 0.9,
  "Maitrise de la ressource foncière": 0.75,
  "Ensemble du parc résidentiel privé": 0.3,
  "Logements sociaux": 0.2,
  "Isolation phonique": 0.3,
  "Isolation thermique": 0.8,
  "Changement des fenêtres/portes d'un bâtiment public": 0.5,
  "Mise en place de l'accessibilité et sécurisation dans les bâtiments ou espace publics": 0.1,
  "Mutabilité, changement de fonction d'un bâtiment ou d'un site": 0.6,
  "Audit ou travaux de rénovation énergétique": 0.95,
  "Audit ou travaux de rénovation énergétique tertiaire": 0.95,
  "Audit ou travaux de rénovation énergétique résidentiel": 0.95,
  "Filière bâtiment": 0.3,
  "Végétalisation d'espaces publics": 0.85,
  Voirie: 0.15,
  "Installation de ralentisseur": 0.05,
  "Installation de miroir de circulation de sécurité routière": 0.05,
  "Mise en place de radars pédagogiques": 0.05,
  "Système de vidéo-protection et dispositifs anti-intrusion": 0.0,
  "Zones à faibles émissions (ZFE)": 0.95,
  "Parc immobilier détenu par un acteur public": 0.3,
  "Décarbonation de flottes de véhicules détenues par la collectivité": 0.95,
  "Décarbonation de flottes de véhicules d'enterprises": 0.95,
  "Report modal du transport de marchandises": 0.9,
  "Carburants alternatifs dans le transport de marchandises": 0.9,
  "Engagement des employeurs dans les nouvelles pratiques de mobilité": 0.8,
  "Voie douce, piste cyclable": 0.8,
  "Subventionnement de l'achat de vélos": 0.75,
  "Vélo (mobilité douce)": 0.8,
  "Randonnée, vélo tourisme, VTT": 0.4,
  "Cours d'eau, lacs et étangs": 0.7,
  "Fret fluvial et ferroviaire": 0.85,
  "Autopartage et location de véhicules": 0.75,
  "Transport à la demande": 0.5,
  Covoiturage: 0.8,
  "Transports en commun": 0.7,
  "Services Express Régionaux Métropolitains (SERM)": 0.7,
  "Infrastructures de recharges électrique": 0.85,
  "Appropriation des enjeux de transition écologique pour les particuliers": 1.0,
  "Filières liées à l'économie circulaire": 0.9,
  "Acquisition d'une parcelle": 0.1,
  "Valorisation des gisements de chaleur fatale dans les sites industriels": 0.95,
  "Décarbonation de sites industriels": 0.95,
  "Crédits carbone labelisés": 0.95,
  "Attractivité des métiers": 0.1,
  Tourisme: 0.15,
  "Tourisme décarboné": 0.85,
  "Appropriation des enjeux de transition écologique pour les entreprises": 1.0,
  "Mise en place de la télémedecine": 0.15,
  "Commande responsable": 0.75,
  "Attractivité économique": 0.1,
  "Innovation, créativité et recherche": 0.15,
  "Technologies numériques et numérisation": 0.15,
  "Personnes âgées": 0.05,
  Handicap: 0.05,
  Famille: 0.05,
  "Egalité des chances": 0.05,
  "Cohésion sociale et inclusion": 0.05,
  Citoyenneté: 0.1,
  "Lutte contre la précarité": 0.1,
  International: 0.05,
  Artisanat: 0.1,
  "Spectacle vivant": 0.05,
  "Industries culturelles et créatives": 0.05,
  Musique: 0.05,
  "Arts plastiques et photographie": 0.05,
  "Culture locale et identité collective": 0.05,
  "Valorisation du patrimoine culturel": 0.1,
  Toiture: 0.25,
  "Mise aux normes": 0.2,
  "Adaptation au changement climatique": 1.0,
  "Confort thermique des transports collectifs et des mobilités actives": 0.85,
  "Adaptation de la filière agricoles au changement climatique": 1.0,
  "Prévention des éboulements et glissement de terrain": 0.5,
  "Retrait-gonflement des argiles": 0.5,
  "Rafraîchissement urbain": 0.9,
  "Lutter contre les logements vacants": 0.5,
  "Plantation d'arbres": 0.85,
  "Gestion des risques": 0.5,
  "Gestion de la circulation": 0.15,
  "Qualité de l'air": 0.9,
  "Plans d'urbanisme": 0.4,
  "Lutte contre la cabanisation": 0.5,
  "Stationnements pour vélos": 0.7,
  Forêt: 0.75,
  "Zone humide": 0.85,
  "Pont, viaduc ou tunnel": 0.1,
  Barrage: 0.3,
  "Ouvrage d'art": 0.1,
  "Commerce, restaurant, café de proximité, ou multiple rural": 0.1,
  "Salle de sport ou gymnase": 0.05,
  Stade: 0.05,
  "City park / city stade / terrain multisports": 0.1,
  Piscine: 0.05,
  "Base nautique": 0.1,
  Cimetière: 0.05,
  "Patrimoine religieux (église, ...)": 0.05,
  "Bibliothèque municipale": 0.05,
  "Crèche / Maison d'assistantes maternelles": 0.05,
  "Maison de santé": 0.05,
  "Aire de jeux": 0.05,
  Ecole: 0.05,
  Gendarmerie: 0.05,
  "Aire éducative": 0.3,
  "Jardin urbain": 0.7,
  "Recyclerie ou ressourcerie locale": 0.85,
  "Restauration collective": 0.4,
  Hôpital: 0.05,
  Friche: 0.6,
  "Tiers-lieu": 0.15,
  Décheterie: 0.6,
  "Bâtiment public": 0.1,
  "Caserne pompiers": 0.05,
  Musée: 0.05,
  "Monument historique": 0.05,
  Montagne: 0.3,
  "Aéroport et aérodrome": 0.05,
  "Clinique vétérinaire": 0.05,
  "Place ou centre-bourg": 0.1,
  "Parking voitures": 0.05,
  "Maison, logement ou immeuble résidentiel": 0.1,
  "Arrêt de bus, abribus": 0.2,
  "Salle des fêtes, salle associative, pôle musical": 0.05,
  "Aire de camping-cars": 0.05,
  "Site industriel": 0.1,
  Cinéma: 0.05,
  Marché: 0.1,
  "Gite, village de vacances": 0.1,
  "ALSH, centre aéré, centre de loisirs": 0.05,
  "Zone d'activité": 0.1,
  Mairie: 0.05,
  "Gare et gare routière": 0.3,
  Port: 0.1,
  "Aire d'accueil des gens du voyage": 0.05,
  "Maison des entreprises": 0.05,
  "Espace de tri sélectif": 0.75,
  "Espaces de congrès et d'exposition": 0.05,
  "Station de traitement des eaux usées (STEP)": 0.6,
  "Micro-folies": 0.05,
  "Réservoir d'eau": 0.3,
  "Edifices patrimoniaux traditionnels ou mémoriels": 0.05,
  "Maison des services, ou maison France services": 0.05,
  "Rénovation bâtiment": 0.3,
  "Rénovation sauf bâtiment (voirie, ...)": 0.2,
  "Stratégie/Plan": 0.2,
  Communication: 0.1,
  Développement: 0.1,
  "Outillage (notamment numérique)": 0.15,
  "Construction bâtiment": 0.15,
  "Construction sauf bâtiment (voirie, ...)": 0.15,
  Entretien: 0.15,
  "Structuration du financement": 0.1,
  Formation: 0.15,
  Dynamisation: 0.1,
  "Etude/Diagnostic": 0.2,
  Sensibilisation: 0.3,
  "Aménagement urbain et restructuration": 0.3,
};
