// Generated file - do not edit directly
export const competencesWithSousCompetences = [
  "Autres interventions de protection civile",
  "Autres services annexes de l'enseignement",
  "Collecte et traitement des déchets",
  "Développement touristique",
  "Enseignement du premier degré",
  "Enseignement du second degré",
  "Enseignement supérieur, professionnel et continu",
  "Foires et marchés",
  "Hébergement et restauration scolaires",
  "Hygiène et salubrité publique",
  "Incendie et secours",
  "Infrastructures de transport",
  "Jeunesse et loisirs",
  "Police, sécurité, justice",
  "Propreté urbaine",
  "Routes et voiries",
  "Santé",
  "Sports",
  "Transports publics (hors scolaire)",
  "Transports scolaires",
  "Action sociale (hors APA et RSA) > Citoyenneté",
  "Action sociale (hors APA et RSA) > Cohésion sociale et inclusion",
  "Action sociale (hors APA et RSA) > Egalité des chances",
  "Action sociale (hors APA et RSA) > Famille et enfance",
  "Action sociale (hors APA et RSA) > Handicap",
  "Action sociale (hors APA et RSA) > Inclusion numérique",
  "Action sociale (hors APA et RSA) > Jeunesse",
  "Action sociale (hors APA et RSA) > Lutte contre la précarité",
  "Action sociale (hors APA et RSA) > Personnes âgées",
  "Action sociale (hors APA et RSA) > Protection animale",
  "Actions en matière de gestion des eaux > Assainissement des eaux",
  "Actions en matière de gestion des eaux > Cours d'eau / canaux / plans d'eau",
  "Actions en matière de gestion des eaux > Eau pluviale",
  "Actions en matière de gestion des eaux > Eau potable",
  "Actions en matière de gestion des eaux > Eau souterraine",
  "Actions en matière de gestion des eaux > Mers et océans",
  "Agriculture, pêche et agro-alimentaire > Consommation alimentaire",
  "Agriculture, pêche et agro-alimentaire > Déchets alimentaires et/ou agricoles",
  "Agriculture, pêche et agro-alimentaire > Distribution",
  "Agriculture, pêche et agro-alimentaire > Précarité et aide alimentaire",
  "Agriculture, pêche et agro-alimentaire > Production agricole et foncier",
  "Agriculture, pêche et agro-alimentaire > Transformation des produits agricoles",
  "Aménagement des territoires > Foncier",
  "Aménagement des territoires > Friche",
  "Aménagement des territoires > Paysage",
  "Aménagement des territoires > Réseaux",
  "Culture > Arts plastiques et photographie",
  "Culture > Bibliothèques et livres",
  "Culture > Médias et communication",
  "Culture > Musée",
  "Culture > Patrimoine et monuments historiques",
  "Culture > Spectacle vivant",
  "Habitat > Accessibilité",
  "Habitat > Architecture",
  "Habitat > Bâtiments et construction",
  "Habitat > Cimetières et funéraire",
  "Habitat > Equipement public",
  "Habitat > Espace public",
  "Habitat > Espaces verts",
  "Habitat > Logement et habitat",
  "Industrie, commerce et artisanat > Artisanat",
  "Industrie, commerce et artisanat > Commerces et Services",
  "Industrie, commerce et artisanat > Economie locale et circuits courts",
  "Industrie, commerce et artisanat > Economie sociale et solidaire",
  "Industrie, commerce et artisanat > Fiscalité des entreprises",
  "Industrie, commerce et artisanat > Industrie",
  "Industrie, commerce et artisanat > Innovation, créativité et recherche",
  "Industrie, commerce et artisanat > Technologies numériques et numérisation",
  "Industrie, commerce et artisanat > Tiers-lieux",
] as const;

export const competences = [
  "Action sociale (hors APA et RSA)",
  "Actions en matière de gestion des eaux",
  "Agriculture, pêche et agro-alimentaire",
  "Aménagement des territoires",
  "Autres interventions de protection civile",
  "Autres services annexes de l'enseignement",
  "Collecte et traitement des déchets",
  "Culture",
  "Développement touristique",
  "Enseignement du premier degré",
  "Enseignement du second degré",
  "Enseignement supérieur, professionnel et continu",
  "Foires et marchés",
  "Habitat",
  "Hygiène et salubrité publique",
  "Hébergement et restauration scolaires",
  "Incendie et secours",
  "Industrie, commerce et artisanat",
  "Infrastructures de transport",
  "Jeunesse et loisirs",
  "Police, sécurité, justice",
  "Propreté urbaine",
  "Routes et voiries",
  "Santé",
  "Sports",
  "Transports publics (hors scolaire)",
  "Transports scolaires",
] as const;

export const sousCompetences = [
  "Accessibilité",
  "Architecture",
  "Artisanat",
  "Arts plastiques et photographie",
  "Assainissement des eaux",
  "Bibliothèques et livres",
  "Bâtiments et construction",
  "Cimetières et funéraire",
  "Citoyenneté",
  "Cohésion sociale et inclusion",
  "Commerces et Services",
  "Consommation alimentaire",
  "Cours d'eau / canaux / plans d'eau",
  "Distribution",
  "Déchets alimentaires et/ou agricoles",
  "Eau pluviale",
  "Eau potable",
  "Eau souterraine",
  "Economie locale et circuits courts",
  "Economie sociale et solidaire",
  "Egalité des chances",
  "Equipement public",
  "Espace public",
  "Espaces verts",
  "Famille et enfance",
  "Fiscalité des entreprises",
  "Foncier",
  "Friche",
  "Handicap",
  "Inclusion numérique",
  "Industrie",
  "Innovation, créativité et recherche",
  "Jeunesse",
  "Logement et habitat",
  "Lutte contre la précarité",
  "Mers et océans",
  "Musée",
  "Médias et communication",
  "Patrimoine et monuments historiques",
  "Paysage",
  "Personnes âgées",
  "Production agricole et foncier",
  "Protection animale",
  "Précarité et aide alimentaire",
  "Réseaux",
  "Spectacle vivant",
  "Technologies numériques et numérisation",
  "Tiers-lieux",
  "Transformation des produits agricoles",
] as const;
