// Generated file - do not edit directly
export const competences = [
  "Autres interventions de protection civile",
  "Autres services annexes de l'enseignement",
  "Collecte et traitement des déchets",
  "Développement touristique",
  "Enseignement du premier degré",
  "Enseignement du second degré",
  "Enseignement supérieur, professionnel et continu",
  "Foires et marchés",
  "Hébergement et restauration scolaires",
  "Hygiène et salubrité publique",
  "Incendie et secours",
  "Infrastructures de transport",
  "Jeunesse et loisirs",
  "Police, sécurité, justice",
  "Propreté urbaine",
  "Routes et voiries",
  "Santé",
  "Sports",
  "Transports publics (hors scolaire)",
  "Transports scolaires",
  "Action sociale (hors APA et RSA) > Citoyenneté",
  "Action sociale (hors APA et RSA) > Cohésion sociale et inclusion",
  "Action sociale (hors APA et RSA) > Egalité des chances",
  "Action sociale (hors APA et RSA) > Famille et enfance",
  "Action sociale (hors APA et RSA) > Handicap",
  "Action sociale (hors APA et RSA) > Inclusion numérique",
  "Action sociale (hors APA et RSA) > Jeunesse",
  "Action sociale (hors APA et RSA) > Lutte contre la précarité",
  "Action sociale (hors APA et RSA) > Personnes âgées",
  "Action sociale (hors APA et RSA) > Protection animale",
  "Actions en matière de gestion des eaux > Assainissement des eaux",
  "Actions en matière de gestion des eaux > Cours d'eau / canaux / plans d'eau",
  "Actions en matière de gestion des eaux > Eau pluviale",
  "Actions en matière de gestion des eaux > Eau potable",
  "Actions en matière de gestion des eaux > Eau souterraine",
  "Actions en matière de gestion des eaux > Mers et océans",
  "Agriculture, pêche et agro-alimentaire > Consommation alimentaire",
  "Agriculture, pêche et agro-alimentaire > Déchets alimentaires et/ou agricoles",
  "Agriculture, pêche et agro-alimentaire > Distribution",
  "Agriculture, pêche et agro-alimentaire > Précarité et aide alimentaire",
  "Agriculture, pêche et agro-alimentaire > Production agricole et foncier",
  "Agriculture, pêche et agro-alimentaire > Transformation des produits agricoles",
  "Aménagement des territoires > Foncier",
  "Aménagement des territoires > Friche",
  "Aménagement des territoires > Paysage",
  "Aménagement des territoires > Réseaux",
  "Culture > Arts plastiques et photographie",
  "Culture > Bibliothèques et livres",
  "Culture > Médias et communication",
  "Culture > Musée",
  "Culture > Patrimoine et monuments historiques",
  "Culture > Spectacle vivant",
  "Habitat > Accessibilité",
  "Habitat > Architecture",
  "Habitat > Bâtiments et construction",
  "Habitat > Cimetières et funéraire",
  "Habitat > Equipement public",
  "Habitat > Espace public",
  "Habitat > Espaces verts",
  "Habitat > Logement et habitat",
  "Industrie, commerce et artisanat > Artisanat",
  "Industrie, commerce et artisanat > Commerces et Services",
  "Industrie, commerce et artisanat > Economie locale et circuits courts",
  "Industrie, commerce et artisanat > Economie sociale et solidaire",
  "Industrie, commerce et artisanat > Fiscalité des entreprises",
  "Industrie, commerce et artisanat > Industrie",
  "Industrie, commerce et artisanat > Innovation, créativité et recherche",
  "Industrie, commerce et artisanat > Technologies numériques et numérisation",
  "Industrie, commerce et artisanat > Tiers-lieux",
] as const;
