// Generated file - do not edit directly
export const competencesWithSousCompetences = [
  "Autres interventions de protection civile",
  "Autres services annexes de l'enseignement",
  "Collecte et traitement des déchets",
  "Développement touristique",
  "Enseignement du premier degré",
  "Enseignement du second degré",
  "Enseignement supérieur, professionnel et continu",
  "Foires et marchés",
  "Hébergement et restauration scolaires",
  "Hygiène et salubrité publique",
  "Incendie et secours",
  "Infrastructures de transport",
  "Jeunesse et loisirs",
  "Police, sécurité, justice",
  "Propreté urbaine",
  "Routes et voiries",
  "Santé",
  "Sports",
  "Transports publics (hors scolaire)",
  "Transports scolaires",
  "Action sociale (hors APA et RSA)__Citoyenneté",
  "Action sociale (hors APA et RSA)__Cohésion sociale et inclusion",
  "Action sociale (hors APA et RSA)__Egalité des chances",
  "Action sociale (hors APA et RSA)__Famille et enfance",
  "Action sociale (hors APA et RSA)__Handicap",
  "Action sociale (hors APA et RSA)__Inclusion numérique",
  "Action sociale (hors APA et RSA)__Jeunesse",
  "Action sociale (hors APA et RSA)__Lutte contre la précarité",
  "Action sociale (hors APA et RSA)__Personnes âgées",
  "Action sociale (hors APA et RSA)__Protection animale",
  "Actions en matière de gestion des eaux__Assainissement des eaux",
  "Actions en matière de gestion des eaux__Cours d'eau / canaux / plans d'eau",
  "Actions en matière de gestion des eaux__Eau pluviale",
  "Actions en matière de gestion des eaux__Eau potable",
  "Actions en matière de gestion des eaux__Eau souterraine",
  "Actions en matière de gestion des eaux__Mers et océans",
  "Agriculture, pêche et agro-alimentaire__Consommation alimentaire",
  "Agriculture, pêche et agro-alimentaire__Déchets alimentaires et/ou agricoles",
  "Agriculture, pêche et agro-alimentaire__Distribution",
  "Agriculture, pêche et agro-alimentaire__Précarité et aide alimentaire",
  "Agriculture, pêche et agro-alimentaire__Production agricole et foncier",
  "Agriculture, pêche et agro-alimentaire__Transformation des produits agricoles",
  "Aménagement des territoires__Foncier",
  "Aménagement des territoires__Friche",
  "Aménagement des territoires__Paysage",
  "Aménagement des territoires__Réseaux",
  "Culture__Arts plastiques et photographie",
  "Culture__Bibliothèques et livres",
  "Culture__Médias et communication",
  "Culture__Musée",
  "Culture__Patrimoine et monuments historiques",
  "Culture__Spectacle vivant",
  "Habitat__Accessibilité",
  "Habitat__Architecture",
  "Habitat__Bâtiments et construction",
  "Habitat__Cimetières et funéraire",
  "Habitat__Equipement public",
  "Habitat__Espace public",
  "Habitat__Espaces verts",
  "Habitat__Logement et habitat",
  "Industrie, commerce et artisanat__Artisanat",
  "Industrie, commerce et artisanat__Commerces et Services",
  "Industrie, commerce et artisanat__Economie locale et circuits courts",
  "Industrie, commerce et artisanat__Economie sociale et solidaire",
  "Industrie, commerce et artisanat__Fiscalité des entreprises",
  "Industrie, commerce et artisanat__Industrie",
  "Industrie, commerce et artisanat__Innovation, créativité et recherche",
  "Industrie, commerce et artisanat__Technologies numériques et numérisation",
  "Industrie, commerce et artisanat__Tiers-lieux",
] as const;

export const competences = [
  "Action sociale (hors APA et RSA)",
  "Actions en matière de gestion des eaux",
  "Agriculture, pêche et agro-alimentaire",
  "Aménagement des territoires",
  "Autres interventions de protection civile",
  "Autres services annexes de l'enseignement",
  "Collecte et traitement des déchets",
  "Culture",
  "Développement touristique",
  "Enseignement du premier degré",
  "Enseignement du second degré",
  "Enseignement supérieur, professionnel et continu",
  "Foires et marchés",
  "Habitat",
  "Hygiène et salubrité publique",
  "Hébergement et restauration scolaires",
  "Incendie et secours",
  "Industrie, commerce et artisanat",
  "Infrastructures de transport",
  "Jeunesse et loisirs",
  "Police, sécurité, justice",
  "Propreté urbaine",
  "Routes et voiries",
  "Santé",
  "Sports",
  "Transports publics (hors scolaire)",
  "Transports scolaires",
] as const;

export const sousCompetences = [
  "Accessibilité",
  "Architecture",
  "Artisanat",
  "Arts plastiques et photographie",
  "Assainissement des eaux",
  "Bibliothèques et livres",
  "Bâtiments et construction",
  "Cimetières et funéraire",
  "Citoyenneté",
  "Cohésion sociale et inclusion",
  "Commerces et Services",
  "Consommation alimentaire",
  "Cours d'eau / canaux / plans d'eau",
  "Distribution",
  "Déchets alimentaires et/ou agricoles",
  "Eau pluviale",
  "Eau potable",
  "Eau souterraine",
  "Economie locale et circuits courts",
  "Economie sociale et solidaire",
  "Egalité des chances",
  "Equipement public",
  "Espace public",
  "Espaces verts",
  "Famille et enfance",
  "Fiscalité des entreprises",
  "Foncier",
  "Friche",
  "Handicap",
  "Inclusion numérique",
  "Industrie",
  "Innovation, créativité et recherche",
  "Jeunesse",
  "Logement et habitat",
  "Lutte contre la précarité",
  "Mers et océans",
  "Musée",
  "Médias et communication",
  "Patrimoine et monuments historiques",
  "Paysage",
  "Personnes âgées",
  "Production agricole et foncier",
  "Protection animale",
  "Précarité et aide alimentaire",
  "Réseaux",
  "Spectacle vivant",
  "Technologies numériques et numérisation",
  "Tiers-lieux",
  "Transformation des produits agricoles",
] as const;
