export const leviers = [
  "Gestion des forêts et produits bois",
  "Changements de pratiques de fertilisation azotée",
  "Elevage durable",
  "Gestion des haies",
  "Bâtiments & Machines agricoles",
  "Gestion des prairies",
  "Pratiques stockantes",
  "Sobriété foncière",
  "Surface en aire protégée",
  "Résorption des points noirs prioritaires de continuité écologique",
  "Restauration des habitats naturels",
  "Réduction de l'usage des produits phytosanitaires",
  "Développement de l'agriculture biologique et de HVE",
  "Respect d'Egalim pour la restauration collective",
  "Sobriété des bâtiments (résidentiel)",
  "Changement chaudières fioul + rénovation (résidentiel)",
  "Changement chaudières gaz + rénovation (résidentiel)",
  "Rénovation (hors changement chaudières)",
  "Sobriété des bâtiments (tertiaire)",
  "Changement chaudières fioul + rénovation (tertiaire)",
  "Changement chaudières gaz + rénovation (tertiaire)",
  "Gaz fluorés résidentiel",
  "Gaz fluorés tertiaire",
  "Captage de méthane dans les ISDND",
  "Prévention des déchets",
  "Valorisation matière des déchets",
  "Moindre stockage en décharge",
  "Augmentation du taux de collecte",
  "Sobriété dans l'utilisation de la ressource en eau",
  "Protection des zones de captage d'eau",
  "Désimperméabilisation des sols",
  "Electricité renouvelable",
  "Biogaz",
  "Réseaux de chaleur décarbonés",
  "Top 50 sites industriels",
  "Industrie diffuse",
  "Fret décarboné et multimodalité",
  "Efficacité et sobriété logistique",
  "Réduction des déplacements",
  "Covoiturage",
  "Vélo",
  "Transports en commun",
  "Véhicules électriques",
  "Efficacité énergétique des véhicules privés",
  "Bus et cars décarbonés",
  "2 roues (élec&efficacité)",
  "Nucléaire",
  "Bio-carburants",
  "Efficacité des aéronefs",
  "SAF",
  "Confort thermique des transports collectifs et des mobilités actives",
  "Réduction de la vulnérabilité des infrastructures et services de transport",
  "Intégration du confort d’été dans la rénovation et la construction des bâtiments",
  "Réseaux de froid",
  "Réduction de la vulnérabilité du système énergétique au changement climatique",
  "Adaptation des filières et des exploitations agricoles",
  "Performance des services publics de l’eau potable et de l’assainissement",
  "Prévention des éboulements et glissement de terrain",
  "Prévention des inondations par débordement de cours d'eau, notamment via restauration des milieux aquatiques",
  "Prévention des inondations par ruissellement",
  "Renaturation des villes et réduction de l'effet d'îlot de chaleur urbain",
  "Conditionnement du développement urbain et économique à la ressource en eau",
  "Renforcement de la résilience des services de santé",
  "Préparation des services de secours",
  "Résilience des services de communication",
  "Protection et mise à l'abri des personnes vulnérables",
  "Evolution de l’offre touristique de montagne",
  "Evolution de l’offre touristique littorale",
  "Continuité des activités économiques",
  "Prévention des dégâts causés par le retrait-gonflement des argiles",
  "Intégration de l’élévation du niveau des mers dans l’aménagement du littoral",
  "Préservation des sites culturels et patrimoniaux",
] as const;
